// <auto-generated />
namespace ProducatoriLocali.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addsomefields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addsomefields));
        
        string IMigrationMetadata.Id
        {
            get { return "202110211949402_Add some fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
